name: Test
on:
  pull_request:
    types: [opened]
  workflow_dispatch :
env :
  API_URL : "https://main.dev.api.zscwp.io"
  AUTH_URL : "https://dev-auth.zscwp.io"
jobs:
 example_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses : ZscalerCWP/Zscaler-IaC-Action@v0.3.1
        id : iac-scan
        with:
          client_id : ${{ secrets.ZSCANNER_CLIENT_ID }}
          client_secret : ${{ secrets.ZSCANNER_CLIENT_SECRET }}
          fail_build : 'true'
          output_format : 'human+github-sarif'
          region : 'CUSTOM'
      - run : echo ${{ steps.iac-scan.outputs.sarif_file_path }}
      - name: Upload SARIF file
        if: ${{ success() || failure() && (steps.iac-scan.outputs.sarif_file_path != '') }}
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.iac-scan.outputs.sarif_file_path }}
